#!/usr/bin/env python3
"""
Generate TypeScript mock module for misfit statistics from real .resp file.

This script reads a CSEM response file, computes misfit statistics using the
calculate_misfit_statistics function from the backend, and outputs a TypeScript
module that exports generateMisfitStatsMockData() with the real calculated data.

Usage:
    python scripts/generate_misfit_stats_mock.py

The input file path is hardcoded as a constant. The output is written to
frontend/src/mocks/misfitStatsMock.ts
"""

import sys
import json
from pathlib import Path

# Add backend to path so we can import the parser
backend_path = Path(__file__).parent.parent / "backend"
sys.path.insert(0, str(backend_path))

from csem_datafile_parser import CSEMDataFileReader, calculate_misfit_statistics

# Input/output paths
INPUT_FILE = "/Users/yli3354/GaTech Dropbox/Yinchu Li/papers/Yinchu/Project/EMAGE/2024Shumagin/data_publishment/202406mainP90.24.resp"
OUTPUT_FILE = (
    Path(__file__).parent.parent / "frontend" / "src" / "mocks" / "misfitStatsMock.ts"
)


def read_and_calculate_misfit_stats(file_path: str) -> dict:
    """
    Read a .resp file and calculate misfit statistics.

    Args:
        file_path: Path to the .resp file

    Returns:
        Dictionary containing misfit statistics grouped by Rx, Tx, Range, and Freq
    """
    # Read the file
    reader = CSEMDataFileReader(file_path)

    # Initialize data blocks
    data = reader.data_block_init(reader.blocks["Data"])
    tx_data = reader.tx_data_block_init(reader.blocks["Tx"])
    rx_data = reader.rx_data_block_init(reader.blocks["Rx"], rx_type="CSEM")

    # Merge data with Rx and Tx information
    merged_df = reader.merge_data_rx_tx(data, rx_data, tx_data)

    # Convert to list of records for calculate_misfit_statistics
    # Need columns: Type, Y_rx, Y_tx, Freq_id, Residual
    records = merged_df[["Type", "Y_rx", "Y_tx", "Freq_id", "Residual"]].to_dict(
        "records"
    )

    # Calculate misfit statistics
    misfit_stats = calculate_misfit_statistics(records)

    return misfit_stats


def format_ts_data_point(point: dict) -> str:
    """Format a single data point as TypeScript object literal."""
    items = []
    for key, value in point.items():
        if isinstance(value, (int, float)):
            # Format numbers with appropriate precision
            if key == "Freq_id":
                items.append(f"{key}: {int(value)}")
            else:
                items.append(f"{key}: {value:.6f}")
        else:
            items.append(f"{key}: {json.dumps(value)}")
    return "{ " + ", ".join(items) + " }"


def format_ts_array(data_points: list) -> str:
    """Format array of data points as TypeScript array."""
    if not data_points:
        return "[]"

    lines = ["["]
    for i, point in enumerate(data_points):
        comma = "," if i < len(data_points) - 1 else ""
        lines.append(f"        {format_ts_data_point(point)}{comma}")
    lines.append("      ]")
    return "\n".join(lines)


def generate_typescript_module(misfit_stats: dict, output_path: Path):
    """
    Generate TypeScript module with the misfit statistics data.

    Args:
        misfit_stats: Dictionary containing misfit statistics
        output_path: Path where the TypeScript file will be written
    """

    ts_content = (
        """/**
 * Mock misfit statistics data for demo mode.
 * Shaped from the backend /api/misfit_stats output schema.
 * 
 * THIS FILE IS AUTO-GENERATED BY scripts/generate_misfit_stats_mock.py
 * DO NOT EDIT MANUALLY
 */

type RMSDataPoint = {
  Y_rx_km?: number;
  Y_tx_km?: number;
  Y_range_km?: number;
  Freq_id?: number;
  RMS: number;
};

type MisfitStatsData = {
  byRx: {
    amplitude: RMSDataPoint[];
    phase: RMSDataPoint[];
  };
  byTx: {
    amplitude: RMSDataPoint[];
    phase: RMSDataPoint[];
  };
  byRange: {
    amplitude: RMSDataPoint[];
    phase: RMSDataPoint[];
  };
  byFreq: {
    amplitude: RMSDataPoint[];
    phase: RMSDataPoint[];
  };
};

/**
 * Generate real calculated misfit statistics data from CSEM response file.
 * Used when VITE_DEMO_MODE is enabled to avoid backend calls.
 */
export function generateMisfitStatsMockData(): MisfitStatsData {
  return {
    byRx: {
      amplitude: """
        + format_ts_array(misfit_stats["byRx"]["amplitude"])
        + """,
      phase: """
        + format_ts_array(misfit_stats["byRx"]["phase"])
        + """,
    },
    byTx: {
      amplitude: """
        + format_ts_array(misfit_stats["byTx"]["amplitude"])
        + """,
      phase: """
        + format_ts_array(misfit_stats["byTx"]["phase"])
        + """,
    },
    byRange: {
      amplitude: """
        + format_ts_array(misfit_stats["byRange"]["amplitude"])
        + """,
      phase: """
        + format_ts_array(misfit_stats["byRange"]["phase"])
        + """,
    },
    byFreq: {
      amplitude: """
        + format_ts_array(misfit_stats["byFreq"]["amplitude"])
        + """,
      phase: """
        + format_ts_array(misfit_stats["byFreq"]["phase"])
        + """,
    },
  };
}
"""
    )

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(ts_content, encoding="utf-8")
    print(f"Generated TypeScript mock module at: {output_path}")


def main():
    """Main entry point."""
    print(f"Reading CSEM response file: {INPUT_FILE}")

    try:
        misfit_stats = read_and_calculate_misfit_stats(INPUT_FILE)
        print(f"Calculated misfit statistics:")
        print(
            f"  byRx: {len(misfit_stats['byRx']['amplitude'])} amplitude, {len(misfit_stats['byRx']['phase'])} phase"
        )
        print(
            f"  byTx: {len(misfit_stats['byTx']['amplitude'])} amplitude, {len(misfit_stats['byTx']['phase'])} phase"
        )
        print(
            f"  byRange: {len(misfit_stats['byRange']['amplitude'])} amplitude, {len(misfit_stats['byRange']['phase'])} phase"
        )
        print(
            f"  byFreq: {len(misfit_stats['byFreq']['amplitude'])} amplitude, {len(misfit_stats['byFreq']['phase'])} phase"
        )

        generate_typescript_module(misfit_stats, OUTPUT_FILE)
        print("SUCCESS: Mock data generated successfully")

    except Exception as e:
        print(f"ERROR: Failed to generate mock data: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
